//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class A_png
    {
        public const string BundleName = "a_png";
        public const string A = "a";
    }
    public class Assetobj_1_prefab
    {
        public const string BundleName = "assetobj 1_prefab";
        public const string ASSETOBJ_1 = "assetobj 1";
    }
    public class Assetobj_2_prefab
    {
        public const string BundleName = "assetobj 2_prefab";
        public const string ASSETOBJ_2 = "assetobj 2";
    }
    public class Assetobj_3_prefab
    {
        public const string BundleName = "assetobj 3_prefab";
        public const string ASSETOBJ_3 = "assetobj 3";
    }
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "assetobj";
    }
    public class B_png
    {
        public const string BundleName = "b_png";
        public const string B = "b";
    }
    public class C_png
    {
        public const string BundleName = "c_png";
        public const string C = "c";
    }
    public class Imageprefaba_prefab
    {
        public const string BundleName = "imageprefaba_prefab";
        public const string IMAGEPREFABA = "imageprefaba";
    }
    public class Imageprefabb_prefab
    {
        public const string BundleName = "imageprefabb_prefab";
        public const string IMAGEPREFABB = "imageprefabb";
    }
    public class Imageprefabc_prefab
    {
        public const string BundleName = "imageprefabc_prefab";
        public const string IMAGEPREFABC = "imageprefabc";
    }
    public class Panel_prefab
    {
        public const string BundleName = "panel_prefab";
        public const string PANEL = "panel";
    }
    public class Panelhome_prefab
    {
        public const string BundleName = "panelhome_prefab";
        public const string PANELHOME = "panelhome";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SCENERES = "sceneres";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string SPRITEATLAS = "spriteatlas";
    }
    public class Textureexample1_png
    {
        public const string BundleName = "textureexample1_png";
        public const string TEXTUREEXAMPLE1 = "textureexample1";
    }
    public class Uibasicpanel_prefab
    {
        public const string BundleName = "uibasicpanel_prefab";
        public const string UIBASICPANEL = "uibasicpanel";
    }
    public class Uimultipanel_prefab
    {
        public const string BundleName = "uimultipanel_prefab";
        public const string UIMULTIPANEL = "uimultipanel";
    }
    public class Uipanelwithimageprefab_prefab
    {
        public const string BundleName = "uipanelwithimageprefab_prefab";
        public const string UIPANELWITHIMAGEPREFAB = "uipanelwithimageprefab";
    }
    public class Uistackpanel1_prefab
    {
        public const string BundleName = "uistackpanel1_prefab";
        public const string UISTACKPANEL1 = "uistackpanel1";
    }
    public class Uistackpanel2_prefab
    {
        public const string BundleName = "uistackpanel2_prefab";
        public const string UISTACKPANEL2 = "uistackpanel2";
    }
}
